"""empty message

Revision ID: 02cc709144ef
Revises: 99491f348642
Create Date: 2020-07-29 22:55:04.449051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cc709144ef'
down_revision = '99491f348642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
