"""empty message

Revision ID: 13dfecddfbcb
Revises: 7b52e9203be3
Create Date: 2020-07-29 22:10:56.332845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dfecddfbcb'
down_revision = '7b52e9203be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.Integer(), nullable=False, comment='Стоимость предмета'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
