"""Python 32 -> 64

Revision ID: 17183d9f6802
Revises: ae153e1f8b91
Create Date: 2020-06-20 19:49:19.264264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17183d9f6802'
down_revision = 'ae153e1f8b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
