"""empty message

Revision ID: 22b28cb9bc7d
Revises: 13dfecddfbcb
Create Date: 2020-07-29 22:11:50.028253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b28cb9bc7d'
down_revision = '13dfecddfbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False, comment='Стоимость предмета'))
    # ### end Alembic commands ###
