"""STABLE2021

Revision ID: 3521c5757a80
Revises: bd2a265a2642
Create Date: 2021-12-06 00:27:27.913278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3521c5757a80'
down_revision = 'bd2a265a2642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
