"""empty message

Revision ID: 3bd761c117c7
Revises: d3bb3509fec7
Create Date: 2020-07-30 00:10:16.874181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd761c117c7'
down_revision = 'd3bb3509fec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('item', sa.String(), nullable=False, comment='Продаваемый предмет'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'item')
    # ### end Alembic commands ###
