"""Added new table with items

Revision ID: 4de99c1d8d8b
Revises: 17183d9f6802
Create Date: 2020-06-26 23:25:16.904623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de99c1d8d8b'
down_revision = '17183d9f6802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Название предмета'),
    sa.Column('attack_boost', sa.Integer(), nullable=False, comment='Повышение урона'),
    sa.Column('defence_boost', sa.Integer(), nullable=False, comment='Повышение защиты'),
    sa.Column('rank', sa.String(), nullable=False, comment='Ранг для получения'),
    sa.Column('quality', sa.String(), nullable=False, comment='Качество'),
    sa.Column('item_class', sa.String(), nullable=False, comment='Оружие или броня'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Стоимость предмета'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
