"""update user

Revision ID: 63c48a55350f
Revises: 4de99c1d8d8b
Create Date: 2020-07-27 20:31:58.028675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c48a55350f'
down_revision = '4de99c1d8d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('healing', sa.Boolean(), nullable=True, comment='Лечение'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'healing')
    # ### end Alembic commands ###
