"""empty message

Revision ID: 7185e7032909
Revises: 3bd761c117c7
Create Date: 2020-07-30 19:20:07.059703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7185e7032909'
down_revision = '3bd761c117c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('comment', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='comment'))
    # ### end Alembic commands ###
