"""empty message

Revision ID: 7b52e9203be3
Revises: ed7b10e07f15
Create Date: 2020-07-29 22:08:21.198566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b52e9203be3'
down_revision = 'ed7b10e07f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ид операции'),
    sa.Column('item', sa.Integer(), nullable=False, comment='Продаваемый предмет'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Цена предмета'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ИД продавца'),
    sa.Column('comment', sa.String(length=30), nullable=True, comment='comment'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
