"""first migration

Revision ID: 931132a683ea
Revises: 
Create Date: 2020-07-29 22:04:01.306006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931132a683ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
