"""empty message

Revision ID: 99491f348642
Revises: 22b28cb9bc7d
Create Date: 2020-07-29 22:53:02.608618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99491f348642'
down_revision = '22b28cb9bc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('rank', sa.String(length=1), nullable=False, comment='Ранг'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'rank')
    # ### end Alembic commands ###
