"""rm username

Revision ID: ae153e1f8b91
Revises: 3e83d5b1e735
Create Date: 2020-06-15 21:21:28.792869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae153e1f8b91'
down_revision = '3e83d5b1e735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Имя'))
    # ### end Alembic commands ###
