"""delete stages

Revision ID: b043d99687a3
Revises: 4ee5ecea15e1
Create Date: 2020-07-28 20:51:27.908685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b043d99687a3'
down_revision = '4ee5ecea15e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stage', sa.INTEGER(), autoincrement=False, nullable=False, comment='Этаж'))
    # ### end Alembic commands ###
