"""empty message

Revision ID: d3bb3509fec7
Revises: 02cc709144ef
Create Date: 2020-07-29 22:55:22.384051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bb3509fec7'
down_revision = '02cc709144ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
