"""empty message

Revision ID: d5044f44e0aa
Revises: 
Create Date: 2020-08-04 23:01:10.304763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5044f44e0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID'),
    sa.Column('username', sa.String(), server_default='noname', nullable=False, comment='Имя'),
    sa.Column('rank', sa.String(length=1), server_default='-', nullable=False, comment='Ранг'),
    sa.Column('lvl', sa.Integer(), server_default='1', nullable=False, comment='Уровень'),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False, comment='Опыт'),
    sa.Column('damage', sa.Integer(), server_default='3', nullable=False, comment='Наносимый урон'),
    sa.Column('weapon', sa.Integer(), nullable=True, comment='Оружие'),
    sa.Column('health', sa.Integer(), server_default='5', nullable=False, comment='Здоровье'),
    sa.Column('max_health', sa.Integer(), server_default='5', nullable=False, comment='Макс. Здоровье'),
    sa.Column('defence', sa.Integer(), server_default='5', nullable=False, comment='Защита'),
    sa.Column('max_defence', sa.Integer(), server_default='5', nullable=False, comment='Макс. Защита'),
    sa.Column('armor', sa.Integer(), nullable=True, comment='Броня'),
    sa.Column('level_points', sa.Integer(), server_default='0', nullable=False, comment='Очки повышения'),
    sa.Column('inventory', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False, comment='Инвентарь'),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False, comment='Баланс'),
    sa.Column('heal_potions', sa.Integer(), server_default='1', nullable=False, comment='Лечебное зелье'),
    sa.Column('abilities', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False, comment='Способности'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
