"""empty message

Revision ID: d76be9409b5f
Revises: d5044f44e0aa
Create Date: 2020-08-05 20:30:30.521059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76be9409b5f'
down_revision = 'd5044f44e0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abilities', 'ability_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abilities', sa.Column('ability_class', sa.VARCHAR(), autoincrement=False, nullable=False, comment='attack or defence'))
    # ### end Alembic commands ###
