"""empty message

Revision ID: ed7b10e07f15
Revises: 931132a683ea
Create Date: 2020-07-29 22:05:51.806428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7b10e07f15'
down_revision = '931132a683ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Название предмета'),
    sa.Column('attack_boost', sa.Integer(), nullable=False, comment='Повышение урона'),
    sa.Column('defence_boost', sa.Integer(), nullable=False, comment='Повышение защиты'),
    sa.Column('rank', sa.String(), nullable=False, comment='Ранг для получения'),
    sa.Column('quality', sa.String(), nullable=False, comment='Качество'),
    sa.Column('item_class', sa.String(), nullable=False, comment='Оружие или броня'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID'),
    sa.Column('username', sa.String(), nullable=False, comment='Имя'),
    sa.Column('rank', sa.String(length=1), nullable=False, comment='Ранг'),
    sa.Column('lvl', sa.Integer(), nullable=False, comment='Уровень'),
    sa.Column('xp', sa.Integer(), nullable=False, comment='Опыт'),
    sa.Column('damage', sa.Integer(), nullable=False, comment='Наносимый урон'),
    sa.Column('weapon', sa.Integer(), nullable=True, comment='Оружие'),
    sa.Column('health', sa.Integer(), nullable=False, comment='Здоровье'),
    sa.Column('max_health', sa.Integer(), nullable=False, comment='Макс. Здоровье'),
    sa.Column('defence', sa.Integer(), nullable=False, comment='Защита'),
    sa.Column('max_defence', sa.Integer(), nullable=False, comment='Макс. Защита'),
    sa.Column('armor', sa.Integer(), nullable=True, comment='Броня'),
    sa.Column('level_points', sa.Integer(), nullable=False, comment='Очки повышения'),
    sa.Column('inventory', sa.ARRAY(sa.Integer()), nullable=False, comment='Инвентарь'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='Баланс'),
    sa.Column('heal_potions', sa.Integer(), nullable=False, comment='Лечебное зелье'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
